---
- name: Deploy Docker containers via Docker-Ansible Role
  hosts: all
  remote_user: root
  gather_facts: true

  vars_files:
    - vault.yml

  tasks:
    - name: Create config dirs
      ansible.builtin.file:
        state: directory
        mode: "0755"
        path: "{{ item.path | dirname }}"
      loop: "{{ docker_config_files }}"
      tags:
        - docker-container
      when: docker_config_files is defined

    - name: Create config files
      # Comment
      ansible.builtin.copy:
        dest: "{{ item.path }}"
        mode: "0755"
        content: "{{ item.config | string }}"
      loop: "{{ docker_config_files }}"
      tags:
        - docker-container
      when: docker_config_files is defined

    - name: Add docker role
      ansible.builtin.import_role:
        name: docker
