---
- name: Create systemd file for docker container
  template:
    src: docker-container.service.j2
    dest: "/etc/systemd/system/docker-{{ item.key }}.service"
    mode: 0755
  with_dict: "{{ docker_containers }}"

- name: Update systemctl
  command: systemctl daemon-reload

- name: Register docker container service
  command: "systemctl enable docker-{{ item.key }}.service"
  with_dict: "{{ docker_containers }}"