---

- name: Configure systemd services for standalone Docker containers
  ansible.builtin.include_tasks: docker-container-systemd.yml
  when:
    - docker_containers is defined
    - docker_containers | length > 0

- name: Configure systemd services for docker-compose containers
  ansible.builtin.include_tasks: docker-compose-systemd.yml
  loop: "{{ docker_compose_projects }}"
  loop_control:
    loop_var: project_item
  when:
    - docker_compose_projects is defined
    - docker_compose_projects | length > 0
