---

- name: Configure systemd services for standalone Docker containers
  ansible.builtin.include_tasks:
    file: docker-container-systemd.yml
  when:
    - docker_containers is defined
  tags:
    - docker-container
    - docker-container-systemd

- name: Configure systemd services for docker-compose containers
  ansible.builtin.include_tasks:
    file: docker-compose-systemd.yml
  loop: "{{ docker_compose_projects }}"
  loop_control:
    loop_var: project_item
  when:
    - docker_compose_projects is defined
  tags:
    - docker-container
    - docker-container-systemd
