---
- name: Create systemd files for docker containers
  template:
    src: docker-container.service.j2
    dest: "/etc/systemd/system/docker-{{ item.key }}.service"
    mode: 0755
  with_dict: "{{ docker_containers }}"
  register: docker_service

#- name: Register docker container service
#  command: "systemctl enable /etc/systemd/system/docker-{{ item.key }}.service"
#  with_dict: "{{ docker_containers }}"
#  when: docker_service.changed
#
#- name: Update systemctl
#  command: systemctl daemon-reload
#  when: docker_service.changed
#
#- name: Register docker container service
#  command: "systemctl restart docker-{{ item.key }}.service"
#  with_dict: "{{ docker_containers }}"
#  when: docker_service.changed

- name: Register docker container service
  command: "systemctl restart docker-{{ item.key }}.service"
  with_dict: "{{ docker_containers }}"
  when: docker_service.changed
