---
- name: Create standalone Docker containers
  ansible.builtin.include_tasks:
    file: docker-container-setup.yml
  when:
    - docker_containers is defined
    - (docker_containers | length) > 0

- name: Create docker-compose containers
  ansible.builtin.include_tasks:
    file: docker-compose-setup.yml
  when:
    - docker_compose_projects is defined
    - (docker_compose_projects | length) > 0
