---

- name: "Ensure directory paths exist for Docker Volume"
  file:
    state: directory
    path: "{{ item.1.split(':')[0] }}"
  with_subelements:
    - "{{ docker_containers }}"
    - volumes
  when: item.1.split(':')[0] is search('/data/')

- name: Create Docker Containers
  docker_container:
    name: "{{ item.key }}"
    hostname: "{{ item.key }}"
    image: "{{ item.value.image }}"
    env: "{{ item.value.env | default({}) }}"
    state: present
    pull: "{{ item.value.pull | default('no') }}"
    comparisons:
      image: strict
      volumes: strict
      env: strict
      devices: strict
    recreate: no
    network_mode: "{{ item.value.network_mode | default('bridge') }}"
    networks: "{{ item.value.networks | default([]) }}"
    published_ports: "{{ item.value.ports | default([]) }}"
    volumes: "{{ item.value.volumes | default([]) }}"
    devices: "{{ item.value.devices | default([]) }}"
    command: "{{ item.value.command | default([]) }}"
    links: "{{ item.value.links | default([]) }}"
    privileged: "{{ item.value.privileged | default('no') }}"
    networks_cli_compatible: |
      {% if item.value.networks is defined %}
        yes
      {% else %}
        no
      {% endif %}
    log_driver: journald
    log_options:
      tag: "{{ item.key }}"
  with_dict: "{{ docker_containers }}"