---
- name: Create systemd files for docker containers
  template:
    src: docker-container.service.j2
    dest: "/etc/systemd/system/docker-{{ item.key }}.service"
    mode: 0755
  with_dict: "{{ docker_containers }}"
  register: docker_service

- name: "Register, Enable, and Start Docker Container Services"
  systemd:
    name: "docker-{{ item.key }}"
    state: "{% if docker_service.changed %}restarted{% else %}started{% endif %}"
    enabled: yes
    daemon_reload: yes
  with_dict: "{{ docker_containers }}"
