---
- name: Create systemd files for docker containers
  template:
    src: docker-container.service.j2
    dest: "/etc/systemd/system/docker-{{ item.key }}.service"
    mode: 0755
  with_dict: "{{ docker_containers }}"
  register: docker_service

- name: "Register, Enable, and Start Docker Container Services"
  systemd:
    name: "docker-{{ item.key }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_dict: "{{ docker_containers }}"

- name: Restart docker-container systemd service if systemd files are updated # noqa 503
  systemd:
    name: "docker-{{ item.key }}"
    state: restarted
    enabled: yes
    daemon_reload: yes
  with_dict: "{{ docker_containers }}"
  when: docker_service.changed
