---

- name: Create Docker Containers
  docker_container:
    name: "{{ item.key }}"
    image: "{{ item.value.image }}"
    env: "{{ item.value.env | default({}) }}"
    state: started
    pull: "{{ item.value.pull | default('no') }}"
    restart_policy: always
    recreate: no
    network_mode: "{{ item.value.network_mode | default('bridge') }}"
    published_ports: "{{ item.value.ports | default([]) }}"
    volumes: "{{ item.value.volumes | default([]) }}"
    devices: "{{ item.value.devices | default([]) }}"
    command: "{{ item.value.command | default([]) }}"
    privileged: "{{ item.value.privileged | default('no') }}"
    log_driver: syslog
    log_options:
      tag: "{{ item.key }}"
  with_dict: "{{ docker_containers }}"
