---

- name: Configure systemd services for standalone Docker containers
  include_tasks: docker-container-systemd.yml
  when:
    - (docker_containers is defined) and (docker_containers | length > 0 )

- name: Configure systemd services for docker-compose containers
  include_tasks: docker-compose-systemd.yml
  loop: "{{ docker_compose_projects }}"
  loop_control:
    loop_var: project_item
  when:
    - (docker_compose_projects is defined) and (docker_compose_projects | length > 0)



# - name: Create systemd files for docker containers
#   template:
#     src: docker-container.service.j2
#     dest: "/etc/systemd/system/docker-{{ item.key|regex_replace('_','-') }}.service"
#     mode: 0755
#   loop: "{{ docker_containers | dict2items }}"
#   loop_control:
#     label: "{{ item.key }}"
#   register: docker_service

# - name: "Register, Enable, and Start Docker Container Services"
#   systemd:
#     name: "docker-{{ item.key|regex_replace('_','-') }}.service"
#     state: "{% if docker_service.changed %}restarted{% else %}started{% endif %}"
#     enabled: yes
#     daemon_reload: yes
#   loop: "{{ docker_containers | dict2items }}"
#   loop_control:
#     label: "{{ item.key }}"

