---
- name: docker-nvidia-grid-driver | Nvidia grid repository setup [Debian]
  when:
    - ansible_os_family == "Debian"
  block:
    - name: docker-nvidia-grid-driver | Install Nvidia Grid repository
      ansible.builtin.deb822_repository:
        name: "{{ docker_vgpu.repo_name }}"
        types: deb
        enabled: true
        state: present
        uris: "{{ docker_vgpu.repo_url }}"
        suites: "{{ docker_vgpu.repo_suites }}"
        components: "{{ docker_vgpu.repo_components }}"
        signed_by: "{{ docker_vgpu.pgp_url }}"
        by_hash: true
        allow_weak: true
      register: deb_repo_added
      until:
        - deb_repo_added is success

    - name: docker-nvidia-grid-driver | Update APT Repos
      ansible.builtin.apt:
        update_cache: true
      register: cache_updated
      until:
        - cache_updated is success

- name: docker-nvidia-grid-driver | Nvidia Grid repository setup [RHEL]
  when:
    - ansible_os_family == "RedHat"
  block:
    - name: docker-nvidia-grid-driver | Install Nvidia Grid Repository
      ansible.builtin.yum_repository:
        name: "{{ docker_vgpu.repo_name }}"
        baseurl:
          - "{{ docker_vgpu.repo_url }}/$releasever/BaseOS/$basearch/os"
        state: present
        description: Local Nvidia Grid Repository
        enabled: true
        gpgkey:
          - "{{ docker_vgpu.pgp_url }}"
      register: yum_repo_added
      until:
        - yum_repo_added is success

- name: docker-nvidia-grid-driver | Install Nvidia Grid driver
  block:
    - name: docker-nvidia-grid-driver | Wait for locks
      ansible.builtin.include_tasks:
        file: wait_for_locks.yml

    - name: docker-nvidia-grid-driver | Install grid video driver
      ansible.builtin.package:
        name:
          - "{{ docker_vgpu.driver }}"
        state: present
        autoremove: true
      register: install_nvidia_drivers
      until: install_nvidia_drivers is not failed
      notify: Reload Docker

- name: docker-nvidia-grid-driver | Install nvidia grid license
  block:
    - name: "Create /etc/nvidia/ClientConfigToken directory"
      ansible.builtin.file:
        dest: /etc/nvidia/ClientConfigToken
        state: directory
        mode: "0755"
      when:
        - docker_vgpu.enabled | default(false)
        - docker_vgpu.license_url | default(none) is string

    - name: docker-nvidia-grid-driver | Download nvidia grid license token
      ansible.builtin.uri:
        url: "{{ docker_vgpu.license_url | trim('/') }}/-/client-token"
        method: GET
        dest: /etc/nvidia/ClientConfigToken/
        validate_certs: false
        mode: "0644"
      when:
        - docker_vgpu.enabled | default(false)
        - docker_vgpu.license_url | default(none) is string
