---
# - name: Set empty array for Docker daemon.json if not found
#   when:
#     - not docker_daemon_json.stat.exists
#   block:
#     - name: Set empty array for docker daemon.json
#       ansible.builtin.set_fact:
#         docker_daemon_config: {}

- name: Gather GPU info and set facts for Docker configuration
  when:
    - docker_install_nvidia | default(false) or docker_vgpu.enabled | default(false)
  block:
    - name: Collect GPU info
      ansible.builtin.command:
        cmd: nvidia-smi -L
      register: nvidia_detected
      changed_when: false
      failed_when: false
      check_mode: false
      when:
        - docker_install_nvidia | default(false) or docker_vgpu.enabled | default(false)

    - name: Set 'has_gpu' fact
      ansible.builtin.set_fact:
        has_gpu: true
      when: nvidia_detected.rc == 0

    - name: Parse detected GPUs for inclusion in Docker daemon.json
      ansible.builtin.shell: >-
        set -o pipefail && nvidia-smi --query-gpu=uuid --format=csv,noheader | jq -Rrn --arg prefix "NVIDIAGPU=" '$prefix + inputs'
      args:
        executable: /bin/bash
      register: gpu_resources
      when: has_gpu | default(false)
      changed_when:
        - gpu_resources | default(None) is not none
      check_mode: false

    - name: Print GPU info
      ansible.builtin.debug:
        msg: |
          {{ gpu_resources.stdout_lines | to_nice_json }}
        verbosity: 0
      when: gpu_resources | default(None) is not none

    - name: Update Docker 'swarm' config to present GPU resources
      ansible.builtin.lineinfile:
        backup: true
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
        path: /etc/nvidia-container-runtime/config.toml
      notify: Reload Docker
      when:
        - gpu_resources | default(None) is not none
      loop:
        - regexp: ^#?swarm-resource.*
          line: swarm-resource = "DOCKER_RESOURCE_NVIDIAGPU"
        - regexp: ^#?accept-nvidia-visible-devices-as-volume-mounts.*
          line: accept-nvidia-visible-devices-as-volume-mounts = true
        - regexp: ^#?accept-nvidia-visible-devices-envvar-when-unprivileged.*
          line: accept-nvidia-visible-devices-envvar-when-unprivileged = true

- name: Docker base info
  block:
    - name: Get docker version
      ansible.builtin.command:
        cmd: docker -v
      register: docker_presence
      changed_when: false
      failed_when: false

    - name: Print Docker info
      ansible.builtin.debug:
        msg: "{{ docker_presence.stdout }}"
        verbosity: 0

- name: Docker daemon.json config
  block:
    - name: Check for existing Docker daemon.json
      ansible.builtin.stat:
        path: /etc/docker/daemon.json
      register: docker_daemon_json

    - name: Slurp contents from daemon.json file if present
      ansible.builtin.slurp:
        src: /etc/docker/daemon.json
      register: docker_daemon_configfile
      failed_when: false
      when:
        - docker_daemon_json.stat.exists

    - name: Set Docker daemon.json content to slurpped file contents if found, otherwise set to empty array
      ansible.builtin.set_fact:
        docker_daemon_config: "{{ (docker_daemon_configfile.content | b64decode) if docker_daemon_json.stat.exists else {} }}"

    - name: Print currently held daemon config contents
      ansible.builtin.debug:
        var: docker_daemon_config | to_nice_json
        verbosity: 0

    - name: Combine any defined [docker_daemon_opts] and detected [gpu_resources] into a new JSON array
      ansible.builtin.set_fact:
        docker_daemon_config: |-
          {%- set ns = namespace(configs={}) -%}
          {%- set ns.configs = {} -%}
          {%- set ns.gpus = [] -%}
            {%- if has_gpu | default(false) -%}
              {%- set ns.configs = ns.configs | combine({
                "default-runtime": "nvidia",
                "runtimes": {
                  "nvidia": {
                    "path": "nvidia-container-runtime",
                    "args": []
                  }
                }
              }) -%}
            {%- endif -%}
            {%- if docker_daemon_opts | default(None) is not none -%}
              {%- set ns.configs = ns.configs | combine(docker_daemon_opts) -%}
            {%- endif -%}
            {%- if gpu_resources | default(None) is not none -%}
              {%- for gpu in gpu_resources.stdout_lines -%}
                {%- set ns.gpus = ns.gpus + [
                  gpu
                ] -%}
              {%- endfor -%}
              {%- set ns.configs = ns.configs | combine({
                "node-generic-resources": ns.gpus
              }) -%}
            {%- endif -%}
          {{ ns.configs }}

    - name: Print updated config contents
      ansible.builtin.debug:
        var: docker_daemon_config | to_nice_json
        verbosity: 0

    - name: Write updated configs to Docker daemon.json
      ansible.builtin.copy:
        content: "{{ docker_daemon_config | to_nice_json }}"
        dest: /etc/docker/daemon.json
        mode: "0755"
        backup: true
      notify: Reload Docker

- name: Update docker systemd service
  block:
    - name: Create systemd Docker service.d directory
      ansible.builtin.file:
        path: /etc/systemd/system/docker.service.d
        state: directory
        mode: "0644"
        owner: root
        group: root
      notify: Reload Docker

    - name: Create systemd Docker override config
      ansible.builtin.template:
        src: docker-override.conf.j2
        dest: /etc/systemd/system/docker.service.d/override.conf
        mode: "0644"
      register: docker_override
      notify: Reload Docker

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Register, enable and start or restart docker service
  ansible.builtin.systemd:
    name: docker
    state: "{{ 'restarted' if (docker_requires_reload | default(false)) else 'started' }}"
    enabled: true
    daemon_reload: true
