---

- name: Create systemd files for docker-compose services
  template:
    src: docker-compose.service.j2
    dest: "{% if item.value.container_name is defined %}/etc/systemd/system/docker-{{ item.value.container_name }}.service{% else %}/etc/systemd/system/docker-{{ project_item.project_name }}-{{ item.key }}.service{% endif %}"
    mode: 0755
  loop: "{{ project_item.definition.services|dict2items }}"
  register: docker_compose_service
  loop_control:
    label: "{{ item.key }}"

- name: "Register, Enable, and Start Docker Container Services"
  systemd:
    name: "{% if item.value.container_name is defined %}docker-{{ item.value.container_name }}{% else %}docker-{{ project_item.project_name }}-{{ item.key }}{% endif %}"
    state: "{% if docker_compose_service.changed %}restarted{% else %}started{% endif %}"
    enabled: yes
    daemon_reload: yes
  loop: "{{ project_item.definition.services|dict2items }}"
  loop_control:
    label: "{{ item.key }}"
