---
- name: Create systemd files for standalone Docker containers
  ansible.builtin.template:
    src: docker-container.service.j2
    dest: /etc/systemd/system/docker-{{ item.key | regex_replace('_', '-') }}.service
    mode: "0644"
  loop: "{{ docker_containers | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  register: docker_service
  tags:
    - docker-container
    - docker-container-systemd

- name: Register, enable, and start systemd services for standalone Docker containers
  ansible.builtin.systemd:
    name: docker-{{ item.key | regex_replace('_', '-') }}.service
    state: "{% if docker_service.changed %}restarted{% else %}started{% endif %}"
    enabled: true
    daemon_reload: true
  loop: "{{ docker_containers | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  tags:
    - docker-container
    - docker-container-systemd
