- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: install docker packages
  apt:
    name: "{{ docker_pkgs }}"
    update_cache: yes
    state: present

- name: Create systemd Docker service.d directory
  file:
    path: "/etc/systemd/system/docker.service.d"
    state: directory

- name: Create systemd Docker override config
  template:
    src: docker-override.conf.j2
    dest: "/etc/systemd/system/docker.service.d/override.conf"
    mode: 0755
  register: docker_override

- name: Reload systemd service and restart docker service
  systemd:
    name: "docker"
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: docker_override.changed

- name: uninstall deprecated python2 docker modules
  pip:
    name: "{{ docker_py2_exclude_pkgs }}"
    state: absent
  when: ansible_python.version.major == 2

- name: install python2 docker modules
  pip:
    name: "{{ docker_py2_pkgs }}"
    state: present
  when: ansible_python.version.major == 2

- name: install python3 docker modules
  pip:
    name: "{{ docker_py3_pkgs }}"
    state: present
  when: ansible_python.version.major == 3
