- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: install docker packages
  apt:
    name: "{{ docker_pkgs }}"
    update_cache: yes
    state: latest

- name: install python2 docker modules
  pip:
    name: "{{ docker_py2_pkgs }}"
    state: latest
  when: ansible_python.version.major == 2

- name: install python3 docker modules
  pip:
    name: "{{ docker_py3_pkgs }}"
    state: latest
  when: ansible_python.version.major == 3 
