---
- name: Create systemd files for standalone Docker containers
  template:
    src: docker-container.service.j2
    dest: "/etc/systemd/system/docker-{{ item.key|regex_replace('_','-') }}.service"
    mode: 0755
  loop: "{{ docker_containers | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  register: docker_service

- name: Register, enable, and start systemd services for standalone Docker containers
  systemd:
    name: "docker-{{ item.key|regex_replace('_','-') }}.service"
    state: "{% if docker_service.changed %}restarted{% else %}started{% endif %}"
    enabled: yes
    daemon_reload: yes
  loop: "{{ docker_containers | dict2items }}"
  loop_control:
    label: "{{ item.key }}"