---
- name: Install git
  package:
    name: git
    state: present

- name: Check out docker image repo
  git:
    repo: "{{ item.value.repo }}"
    version: "{{ item.value.branch | default('master') }}"
    dest: "{{ data_mount_root }}/{{ git_directory }}/{{ item.key }}"
  loop: "{{ docker_build_images|dict2items }}"
  register: docker_image_repo

- name: Build Docker Image
  docker_image:
    path: "{{ data_mount_root }}/{{ git_directory }}/{{ item.key }}"
    dockerfile: "{{ item.value.dockerfile | default('Dockerfile') }}"
    name: "{{ item.key }}"
    buildargs: "{{ item.value.buildargs | default({}) }}"
    force: yes
  with_dict: "{{ docker_build_images }}"
  when: docker_image_repo is changed
