---
- name: Install git
  package:
    name: git
    state: present

- name: Check out docker image repo
  git:
    repo: "{{ item.value.repo }}"
    version: "{{ item.value.branch | default('master') }}"
    dest: "{{ data_mount_root }}/{{ git_directory }}/{{ item.key }}"
  loop: "{{ docker_build_images|dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  register: docker_image_repo
  when:
    - docker_build_images is defined
    - docker_build_images != None

- name: Build Docker Image
  docker_image:
    name: "{{ item.item.key }}"
    build:
      path: "{{ data_mount_root }}/{{ git_directory }}/{{ item.item.key }}"
      dockerfile: "{{ item.item.value.dockerfile | default('Dockerfile') }}"
      args: "{{ item.item.value.buildargs | default({}) }}"
      pull: yes
    force_source: yes
    source: build
  loop: "{{ docker_image_repo.results }}"
  loop_control:
    label: "{{ item.item.key }}"
  when:
    - docker_build_images is defined
    - docker_build_images != None
