---
- name: Install git
  package:
    name: git
    state: present

- name: Check out docker image repo
  git:
    repo: "{{ item.value.repo }}"
    version: "{{ item.value.branch | default('master') }}"
    dest: "{{ data_mount_root }}/{{ git_directory }}/{{ item.key }}"
  loop: "{{ docker_build_images|dict2items }}"
  register: docker_image_repo

- name: Build Docker Image
  docker_image:
    build.path: "{{ data_mount_root }}/{{ git_directory }}/{{ item.item.key }}"
    build.dockerfile: "{{ item.item.value.build.dockerfile | default('Dockerfile') }}"
    name: "{{ item.item.key }}"
    build.args: "{{ item.item.value.build.args | default({}) }}"
    force_source: yes
    source: build
  loop: "{{ docker_image_repo.results }}"
  when: item.changed