---
- name: packages_redhat | Wait for locks
  ansible.builtin.include_tasks:
    file: wait_for_locks.yml

- name: packages_redhat | Disable SELinux, Configure FirewallD ports to ACCEPT [RHEL/CentOS]
  block:
    - name: packages_redhat | Disable SELinux
      ansible.posix.selinux:
        state: disabled

    - name: packages_redhat | Configure Firewalld allowed ports
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      loop: "{{ docker_allowed_ports }}"

- name: packages_redhat | Install Docker Community Edition (RHEL Major >= 8)
  when:
    - docker_install_community_edition
  block:
    - name: packages_redhat | Remove OS Repository Docker Packages
      ansible.builtin.package:
        name: "{{ docker_io_pkgs }}"
        state: absent

    - name: packages_redhat | Install Docker GPG Key
      ansible.builtin.rpm_key:
        key: "{{ docker_repo_url }}/{{ ansible_distribution | lower }}/gpg"
        state: present

    - name: packages_redhat | Set up Docker Community Edition Repository
      ansible.builtin.yum_repository:
        baseurl: "{{ docker_repo_url }}/{{ ansible_distribution | lower }}/$releasever/$basearch/{{ docker_ce_version }}"
        name: docker-ce
        description: Docker Community Edition

    - name: packages_redhat | Install Docker Community Edition Packages
      ansible.builtin.package:
        name: "{{ docker_ce_pkgs }}"
        update_cache: true
        state: latest
        update_only: true
      register: docker_pkg_install
      until: docker_pkg_install is not failed
      notify: Reload Docker

- name: packages_redhat | Install Docker from OS Repository
  when:
    - not docker_install_community_edition
  block:
    - name: packages_redhat | Remove Docker Community-Edition Packages
      ansible.builtin.package:
        name: "{{ docker_ce_pkgs }}"
        state: absent

    - name: packages-debian | Remove old repo file
      ansible.builtin.file:
        path: /etc/yum.repos.d/docker-ce.repo
        state: absent

    - name: packages_redhat | Install Docker Packages From OS Repository
      ansible.builtin.package:
        name: "{{ docker_io_pkgs }}"
        update_cache: true
        state: latest
        update_only: true
      register: docker_pkg_install
      until: docker_pkg_install is not failed
      notify: Reload Docker
