---

- name: Install Docker [Debian/Ubuntu]
  import_tasks: install_debian.yml
  when:
    - override_os_family | default(ansible_os_family) == "Debian"

- name: Install Docker [RedHat]
  import_tasks: install_redhat.yml
  when:
    - override_os_family | default(ansible_os_family) == "RedHat"

- name: Start and enable docker-ce services
  block:
    - name: Start and enable docker socket
      systemd:
        name: docker.socket
        state: restarted
        masked: no
        enabled: yes
        daemon_reload: yes
    - name: Start and enable docker service
      systemd:
        name: docker.service
        masked: no
        state: restarted
        enabled: yes
        daemon_reload: yes
  when:
    - docker_install_community_edition

- name: Create systemd override for Docker service
  block:
    - name: Create systemd Docker service.d directory
      file:
        path: "/etc/systemd/system/docker.service.d"
        state: directory

    - name: Create systemd Docker override config
      template:
        src: docker-override.conf.j2
        dest: "/etc/systemd/system/docker.service.d/override.conf"
        mode: 0755
      register: docker_override

    - name: Reload systemd service and restart docker service # noqa 503
      systemd:
        name: "docker.service"
        masked: no
        state: restarted
        enabled: yes
        daemon_reload: yes
      when: docker_override.changed
  when:
    - ansible_os_family == "Debian"

- name: Install Package Dependencies
  package:
    name: "{{ docker_dependency_pkgs }}"
    state: present

- name: Upgrade python-pip
  pip:
    name: pip
    state: present

- name: Install Python Packages
  block:
    - name: install python docker modules
      pip:
        name: "{{ docker_py26_pkgs }}"
        state: present
        executable: pip2
      when:
        - ansible_python.version.minor <= 6
    - name: uninstall deprecated python 2.7 docker modules
      pip:
        name: "{{ docker_py26_pkgs }}"
        state: absent
        executable: pip2
      when:
        - ansible_python.version.minor >= 7
    - name: install python 2.7 docker modules
      pip:
        name: "{{ docker_py27_pkgs }}"
        state: present
        executable: pip2
      when:
        - ansible_python.version.minor >= 7
  when:
    - ansible_python.version.major == 2

- name: Install Python3 Packages
  block:
    - name: install python3 docker modules
      pip:
        name: "{{ docker_py3_pkgs }}"
        state: present
        executable: pip3
  when:
    - ansible_python.version.major == 3
