---
- name: Install Docker [Debian/Ubuntu]
  ansible.builtin.include_tasks:
    file: install_{{ ansible_os_family | lower }}.yml
    apply:
      tags: docker-install
  tags:
    - docker-install
    - docker-install-nvidia

- name: Enable and start or restart docker socket and service
  block:
    - name: Start and enable docker service
      ansible.builtin.systemd:
        name: docker.service
        masked: false
        state: "{{ 'restarted' if (docker_requires_reload | default(false)) else 'started' }}"
        enabled: true
        daemon_reload: true
      register: docker_container_service
      until: docker_container_service is not failed

- name: Wait for locks
  ansible.builtin.include_tasks:
    file: wait_for_locks.yml

- name: Install Package Dependencies
  ansible.builtin.package:
    name: "{{ docker_dependency_pkgs }}"
    state: present

- name: Upgrade python-pip
  ansible.builtin.pip:
    name: pip
    state: present

- name: Install Python Packages
  when:
    - ansible_python.version.major == 2
  block:
    - name: Install python docker modules
      ansible.builtin.pip:
        name: "{{ docker_py26_pkgs }}"
        state: present
        executable: pip2
      when:
        - ansible_python.version.minor <= 6
    - name: Uninstall deprecated python 2.7 docker modules
      ansible.builtin.pip:
        name: "{{ docker_py26_pkgs }}"
        state: absent
        executable: pip2
      when:
        - ansible_python.version.minor >= 7
    - name: Install python 2.7 docker modules
      ansible.builtin.pip:
        name: "{{ docker_py27_pkgs }}"
        state: present
        executable: pip2
      when:
        - ansible_python.version.minor >= 7

- name: Install Python3 Packages
  when:
    - ansible_python.version.major == 3
  block:
    - name: Install python3 docker modules
      ansible.builtin.pip:
        name: "{{ docker_py3_pkgs }}"
        state: present
        executable: pip3

- name: Include Docker daemon.json common tasks
  ansible.builtin.include_tasks:
    file: docker-daemon.yml
  tags:
    - docker-daemon-config
