---
- name: packages-debian | Wait for locks
  ansible.builtin.include_tasks:
    file: wait_for_locks.yml

- name: packages-debian | Install Docker Community Edition
  when:
    - docker_install_community_edition
  block:
    - name: packages-debian | Get dpkg architecture
      ansible.builtin.command: dpkg --print-architecture
      register: dpkg_architecture_result
      changed_when: false

    - name: packages-debian | Set machine architecture
      ansible.builtin.set_fact:
        dpkg_architecture: "{{ dpkg_architecture_result.stdout }}"

    - name: packages-debian | Remove OS Repository Docker Packages
      ansible.builtin.package:
        name: "{{ docker_io_pkgs }}"
        state: absent

    - name: packages-debian | Remove old repo file
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/docker-ce.list
        state: absent

    - name: packages-debian | Add Docker repository and GPG Key
      ansible.builtin.deb822_repository:
        name: docker-ce
        types: deb
        enabled: true
        state: present
        allow_insecure: true
        uris: "{{ docker_repo_url }}/{{ ansible_distribution | lower }}"
        suites: "{{ ansible_distribution_release }}"
        components: "{{ docker_ce_version }}"
        signed_by: "{{ docker_repo_url }}/{{ ansible_distribution | lower }}/gpg"
      register: docker_repo_added

    - name: packages-debian | Install Docker Packages
      ansible.builtin.package:
        name: '{{ docker_ce_pkgs }}'
        update_cache: true
        state: latest
      register: docker_pkg_install
      until: docker_pkg_install is not failed
      notify: Reload Docker

- name: packages-debian | Install Docker from OS Repository
  when:
    - not docker_install_community_edition
  block:
    - name: packages-debian | Remove Docker Community-Edition Packages
      ansible.builtin.package:
        name: "{{ docker_ce_pkgs }}"
        state: absent

    - name: packages-debian | Remove docker-ce repo file
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/docker-ce.list
        state: absent

    - name: packages-debian | Install Docker Packages From OS Repository # noqa package-latest
      ansible.builtin.package:
        name: "{{ docker_io_pkgs }}"
        update_cache: true
        state: latest
      register: docker_pkg_install
      until: docker_pkg_install is not failed
      notify: Reload Docker

- name: packages-debian | Create systemd override for Docker service
  when:
    - ansible_os_family == "Debian"
  block:
    - name: packages-debian | Create systemd Docker service.d directory
      ansible.builtin.file:
        path: /etc/systemd/system/docker.service.d
        state: directory
        mode: "0777"
        owner: root
        group: root
      notify: Reload Docker

    - name: packages-debian | Create systemd Docker override config
      ansible.builtin.template:
        src: docker-override.conf.j2
        dest: /etc/systemd/system/docker.service.d/override.conf
        mode: "0777"
        owner: root
        group: root
      register: docker_override
      notify: Reload Docker
