---
- name: Include os specific vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - always

- name: Include installation tasks
  tags:
    - docker-install
    - docker-install-nvidia
    - docker-daemon-config
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      tags:
        - docker-install

- name: Include container setup tasks
  tags:
    - docker-container
    - docker-container-setup
  ansible.builtin.include_tasks:
    file: container-setup.yml
    apply:
      tags:
        - docker-container
        - docker-container-setup

- name: Include systemd service tasks
  tags:
    - docker-container-systemd
    - docker-container
  ansible.builtin.include_tasks:
    file: container-systemd.yml
    apply:
      tags:
        - docker-container-systemd
        - docker-container
