---
- name: install docker packages
  apt: 
    name: "{{ item }}"
    update_cache: yes 
    state: latest
  with_items: "{{ docker_pkgs }}"

- name: install docker python modules
  pip:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items: "{{ docker_py_pkgs }}"
