---
- import_tasks: docker-install.yml
  tags:
    - dockerinstall

- import_tasks: image-build.yml
  when: docker_build_images is defined
  tags:
    - dockerbuild

- import_tasks: network-setup.yml
  when: docker_networks is defined
  tags:
    - dockernetwork

- import_tasks: container-setup.yml
  when: docker_containers is defined
  tags:
    - dockercontainers

- import_tasks: container-service.yml
  when: docker_containers is defined
  tags:
    - dockercontainers
