---

- name: Include os specific vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_distribution }}.yml"
  tags:
    - always

- name: Import installer
  ansible.builtin.include_tasks:
    file: install.yml
  tags:
    - docker-install

- name: Import image builder
  ansible.builtin.include_tasks:
    file: image-build.yml
  tags:
    - image-build

- name: Import network setup
  ansible.builtin.include_tasks:
    file: network-setup.yml
  tags:
    - docker-network

- name: Import container setup
  ansible.builtin.include_tasks:
    file: container-setup.yml
  tags:
    - docker-container

- name: Import container systemd
  ansible.builtin.include_tasks:
    file: container-systemd.yml
  tags:
    - docker-container
    - docker-container-systemd
