---

- name: Include os specific vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - always

- name: Import installer
  ansible.builtin.import_tasks: install.yml

- name: Import image builder
  ansible.builtin.import_tasks: image-build.yml

- name: Import network setup
  ansible.builtin.import_tasks: network-setup.yml

- name: Import container setup
  ansible.builtin.import_tasks: container-setup.yml
  tags:
    - docker-container

- name: Import container systemd
  ansible.builtin.import_tasks: container-systemd.yml
  tags:
    - docker-container
    - docker-container-systemd
