---

- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - always

- import_tasks: install.yml
  tags:
    - docker-install

- import_tasks: image-build.yml
  tags:
    - docker-build

- import_tasks: network-setup.yml
  tags:
    - docker-network

- import_tasks: container-setup.yml
  tags:
    - docker-container

- import_tasks: container-service.yml
  tags:
    - docker-container
    - docker-container-systemd
