---
- name: Include os specific vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - always

- name: Include installation tasks
  ansible.builtin.include_tasks:
    file: install.yml
  tags:
    - docker-install

- name: Include image build tasks
  ansible.builtin.include_tasks:
    file: image-build.yml
  tags:
    - image-build

- name: Include network setup tasks
  ansible.builtin.include_tasks:
    file: network-setup.yml
  tags:
    - docker-network

- name: Include container setup tasks
  ansible.builtin.include_tasks:
    file: container-setup.yml
  tags:
    - docker-container

- name: Include systemd service tasks
  ansible.builtin.include_tasks:
    file: container-systemd.yml
  tags:
    - docker-container
    - docker-container-systemd
