---

- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- set_fact:
    compose_containers: []
- set_fact:
    compose_networks: []

- import_tasks: install.yml

- import_tasks: image-build.yml
  when: docker_build_images is defined

- import_tasks: network-setup.yml
  when: docker_networks is defined

- import_tasks: container-setup.yml
  when: docker_containers is defined

- import_tasks: container-service.yml
  when: docker_containers is defined
