---

- set_fact:
    compose_networks: "{{ compose_networks + item.networks }}"
  loop: "{{ docker_compose_projects }}"

- name: "Create Docker Networks"
  docker_network:
    name: "{{ item.key }}"
    appends: "{{ item.value.appends | default('no') }}"
    internal: "{{ item.value.internal | default('no') }}"
    scope: "{{ item.value.scope | default('local') }}"
    ipam_config: "{{ item.value.ipam_config | default (omit) }}"
    state: "present"
  loop: "{{ docker_networks | dict2items }}"
  when: item.key not in compose_networks
