---

- name: "Create Docker Networks"
  docker_network:
    name: "{{ item.key }}"
    appends: "{{ item.appends | default('no') }}"
    internal: "{{ item.internal | default('no') }}"
    scope: "{{ item.scope | default('local') }}"
    ipam_config: "{{ item.ipam | default ([]) )}"
    state: "present"
  with_dict: "{{ docker_networks }}"