---

- name: "Create Docker Networks"
  docker_network:
    name: "{{ item.name }}"
    appends: "{{ item.appends | default('no') }}"
    internal: "{{ item.internal | default('no') }}"
    scope: "{{ item.scope | default('local') }}"
    ipam_config: "{{ item.ipam | default ([]) }}"
    state: "present"
  with_items: "{{ docker_networks }}"
