---

- name: "Create Docker Networks"
  docker_network:
    name: "{{ item.key }}"
    appends: "{{ item.value.appends | default('no') }}"
    attachable: "{{ item.value.attachable | default('no') }}"
    internal: "{{ item.value.internal | default('no') }}"
    scope: "{{ item.value.scope | default('local') }}"
    driver: "{{ item.value.driver | default(omit) }}"
    ipam_config: "{{ item.value.ipam_config|default(omit) }}"
    ipam_driver: "{{ item.value.ipam_driver|default(omit) }}"
    state: "present"
  loop: "{{ docker_networks | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when:
    - docker_networks is defined
    - docker_networks != None
