---

- name: "Create Docker Networks"
  docker_network:
    name: "{{ item.key }}"
    appends: "{{ item.value.appends | default('no') }}"
    internal: "{{ item.value.internal | default('no') }}"
    scope: "{{ item.value.scope | default('local') }}"
    ipam_config: "{{ item.value.ipam_config | default (omit) }}"
    state: "present"
  loop: "{{ docker_networks | dict2items }}"
