---
- name: Initramfs requires update
  ansible.builtin.set_fact:
    initramfs_requires_update: true
  when: blacklist_nouveau is changed

- name: Dracut requires update
  ansible.builtin.set_fact:
    dracut_requires_update: true
  when: blacklist_nouveau is changed

- name: Reload docker
  ansible.builtin.set_fact:
    docker_requires_reload: true
